### ISSUE TITLE
Can't download the dataset

### ISSUE THREAD

**Issue by hienphan161** [Oriolrt/SIDTD_Dataset#6]
Hello team. I attempted to execute the following code to download the dataset, but encountered a 404 error.

```
from SIDTD.data.DataLoader.Datasets import *

data = SIDTD(download_original=False, custom_path_to_download=None).download_dataset("templates")  #["you  can choose among templates, clips, clips_cropped and "all" of them]
```

```
--2024-08-19 16:30:52--  http://datasets.cvc.uab.es/SIDTDtemplates.zip
Resolving datasets.cvc.uab.es (datasets.cvc.uab.es)... 158.109.8.18
Connecting to datasets.cvc.uab.es (datasets.cvc.uab.es)|158.109.8.18|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-08-19 16:30:53 ERROR 404: Not Found.
```

**Comment by Bycarkos** [comment]
Hi @hienphan161, Thank you for exposing this error.
 
I reproduced the procedure as it is depicted in the repository and I haven't this error.

![Screenshot_20241030_195751](https://github.com/user-attachments/assets/2380a54d-1b50-41e1-adc8-2f62eeeea08e)

Try to reproduce it another time and if the error persists I'll check it another time.
